server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_db?useSSL=false
    username: root
    password: dfm123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.softsec.app.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.softsec: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则：优先选择本地集群

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
    connection-timeout: 10000
